<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class AdditionalProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── Electronics / Smartphones ──
            [
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'price' => 89990,
                'compare_price' => 99990,
                'discount_percentage' => 10.0,
                'description' => 'Google\'s flagship with the best computational photography and pure Android experience.',
                'short_description' => 'Google flagship with AI camera',
                'category_slug' => 'smartphones',
                'brand_slug' => null,
                'stock_quantity' => 40,
                'is_featured' => true,
                'average_rating' => 4.7,
                'reviews_count' => 178,
                'sales_count' => 890,
                'sku' => 'GGL-PX8P',
                'tags' => ['google', 'pixel', 'smartphone', 'ai'],
                'image' => 'https://images.unsplash.com/photo-1598228723793-52759bba239c?w=600&h=600&fit=crop',
            ],
            [
                'name' => 'OnePlus 12',
                'slug' => 'oneplus-12',
                'price' => 69990,
                'compare_price' => 79990,
                'discount_percentage' => 12.5,
                'description' => 'Flagship killer with Snapdragon 8 Gen 3 and 100W fast charging.',
                'short_description' => 'Flagship killer with fast charging',
                'category_slug' => 'smartphones',
                'brand_slug' => null,
                'stock_quantity' => 60,
                'is_flash_sale' => true,
                'average_rating' => 4.6,
                'reviews_count' => 234,
                'sales_count' => 1100,
                'sku' => 'ONE-12',
                'tags' => ['oneplus', 'smartphone', 'fast-charging'],
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop',
            ],
            [
                'name' => 'Xiaomi Redmi Note 13 Pro',
                'slug' => 'xiaomi-redmi-note-13-pro',
                'price' => 27990,
                'compare_price' => 32990,
                'discount_percentage' => 15.16,
                'description' => 'Budget champion with 200MP camera and AMOLED display.',
                'short_description' => 'Budget phone with 200MP camera',
                'category_slug' => 'smartphones',
                'brand_slug' => null,
                'stock_quantity' => 150,
                'is_best_seller' => true,
                'average_rating' => 4.5,
                'reviews_count' => 567,
                'sales_count' => 4200,
                'sku' => 'XIA-RN13P',
                'tags' => ['xiaomi', 'redmi', 'budget', 'camera'],
                'image' => 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&h=600&fit=crop',
            ],

            // ── Laptops ──
            [
                'name' => 'Dell XPS 15',
                'slug' => 'dell-xps-15',
                'price' => 179990,
                'compare_price' => 199990,
                'discount_percentage' => 10.0,
                'description' => 'Premium ultrabook with InfinityEdge display and Intel i9 processor.',
                'short_description' => 'Premium ultrabook with i9',
                'category_slug' => 'laptops',
                'brand_slug' => null,
                'stock_quantity' => 25,
                'is_featured' => true,
                'average_rating' => 4.7,
                'reviews_count' => 89,
                'sales_count' => 320,
                'sku' => 'DEL-XPS15',
                'tags' => ['dell', 'xps', 'laptop', 'ultrabook'],
                'image' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop',
            ],
            [
                'name' => 'ASUS ROG Strix G16',
                'slug' => 'asus-rog-strix-g16',
                'price' => 149990,
                'compare_price' => 169990,
                'discount_percentage' => 11.77,
                'description' => 'Gaming laptop with RTX 4070 and 165Hz display for competitive gaming.',
                'short_description' => 'Gaming laptop with RTX 4070',
                'category_slug' => 'laptops',
                'brand_slug' => null,
                'stock_quantity' => 30,
                'is_featured' => true,
                'is_best_seller' => true,
                'average_rating' => 4.8,
                'reviews_count' => 156,
                'sales_count' => 670,
                'sku' => 'ASU-ROG16',
                'tags' => ['asus', 'rog', 'gaming', 'laptop'],
                'image' => 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=600&h=600&fit=crop',
            ],
            [
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'slug' => 'lenovo-thinkpad-x1-carbon',
                'price' => 164990,
                'description' => 'Ultra-light business laptop with legendary ThinkPad keyboard.',
                'short_description' => 'Ultra-light business laptop',
                'category_slug' => 'laptops',
                'brand_slug' => null,
                'stock_quantity' => 20,
                'is_new_arrival' => true,
                'average_rating' => 4.6,
                'reviews_count' => 67,
                'sales_count' => 280,
                'sku' => 'LEN-X1C',
                'tags' => ['lenovo', 'thinkpad', 'business', 'ultralight'],
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=600&fit=crop',
            ],

            // ── Audio ──
            [
                'name' => 'AirPods Pro 2nd Gen',
                'slug' => 'airpods-pro-2nd-gen',
                'price' => 27990,
                'compare_price' => 32990,
                'discount_percentage' => 15.16,
                'description' => 'Apple\'s best in-ear earbuds with adaptive ANC and USB-C charging.',
                'short_description' => 'Apple earbuds with adaptive ANC',
                'category_slug' => 'audio',
                'brand_slug' => 'apple',
                'stock_quantity' => 100,
                'is_featured' => true,
                'is_best_seller' => true,
                'average_rating' => 4.8,
                'reviews_count' => 892,
                'sales_count' => 5600,
                'sku' => 'APL-APP2',
                'tags' => ['apple', 'airpods', 'earbuds', 'anc'],
                'image' => 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
            ],
            [
                'name' => 'JBL Charge 5',
                'slug' => 'jbl-charge-5',
                'price' => 14990,
                'compare_price' => 17990,
                'discount_percentage' => 16.68,
                'description' => 'Portable Bluetooth speaker with IP67 waterproof rating and powerbank feature.',
                'short_description' => 'Waterproof portable speaker',
                'category_slug' => 'audio',
                'brand_slug' => null,
                'stock_quantity' => 80,
                'is_flash_sale' => true,
                'average_rating' => 4.7,
                'reviews_count' => 345,
                'sales_count' => 2100,
                'sku' => 'JBL-CH5',
                'tags' => ['jbl', 'speaker', 'bluetooth', 'waterproof'],
                'image' => 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=600&h=600&fit=crop',
            ],
            [
                'name' => 'Samsung Galaxy Buds2 Pro',
                'slug' => 'samsung-galaxy-buds2-pro',
                'price' => 19990,
                'compare_price' => 22990,
                'discount_percentage' => 13.05,
                'description' => 'Premium true wireless earbuds with 360 Audio and intelligent ANC.',
                'short_description' => 'Samsung premium wireless earbuds',
                'category_slug' => 'audio',
                'brand_slug' => 'samsung',
                'stock_quantity' => 70,
                'is_new_arrival' => true,
                'average_rating' => 4.5,
                'reviews_count' => 234,
                'sales_count' => 1500,
                'sku' => 'SAM-GB2P',
                'tags' => ['samsung', 'galaxy-buds', 'wireless', 'anc'],
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=600&h=600&fit=crop',
            ]

            // ── Fashion / Men ──
            [
                'name' => 'Men\'s Leather Jacket',
                'slug' => 'mens-leather-jacket',
                'price' => 5990,
                'compare_price' => 7990,
                'discount_percentage' => 25.03,
                'description' => 'Genuine leather biker jacket with quilted lining for winter style.',
                'short_description' => 'Genuine leather biker jacket',
                'category_slug' => 'mens-clothing',
                'brand_slug' => 'zara',
                'stock_quantity' => 45,
                'is_featured' => true,
                'average_rating' => 4.6,
                'reviews_count' => 89,
                'sales_count' => 430,
                'sku' => 'ZAR-MLJ',
                'tags' => ['jacket', 'leather', 'men', 'winter'],
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Slim Fit Chinos',
                'slug' => 'slim-fit-chinos',
                'price' => 2490,
                'description' => 'Stretch cotton chinos with a modern slim fit. Perfect for casual and smart-casual looks.',
                'short_description' => 'Stretch cotton slim fit chinos',
                'category_slug' => 'mens-clothing',
                'brand_slug' => 'zara',
                'stock_quantity' => 200,
                'is_best_seller' => true,
                'average_rating' => 4.4,
                'reviews_count' => 234,
                'sales_count' => 3100,
                'sku' => 'ZAR-SFC',
                'tags' => ['chinos', 'slim-fit', 'men', 'casual'],
                'image' => 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=600&fit=crop',
            ]

            // ── Fashion / Women ──
            [
                'name' => 'Women\'s Silk Saree',
                'slug' => 'womens-silk-saree',
                'price' => 4990,
                'compare_price' => 5990,
                'discount_percentage' => 16.69,
                'description' => 'Elegant Banarasi silk saree with intricate gold zari work.',
                'short_description' => 'Banarasi silk saree with zari',
                'category_slug' => 'womens-clothing',
                'brand_slug' => null,
                'stock_quantity' => 50,
                'is_featured' => true,
                'average_rating' => 4.8,
                'reviews_count' => 123,
                'sales_count' => 670,
                'sku' => 'GEN-WSS',
                'tags' => ['saree', 'silk', 'women', 'traditional'],
                'image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Women\'s Running Shoes',
                'slug' => 'womens-running-shoes',
                'price' => 8990,
                'description' => 'Lightweight running shoes with responsive cushioning for daily training.',
                'short_description' => 'Lightweight women\'s runners',
                'category_slug' => 'footwear',
                'brand_slug' => 'nike',
                'stock_quantity' => 90,
                'is_flash_sale' => true,
                'average_rating' => 4.5,
                'reviews_count' => 178,
                'sales_count' => 1200,
                'sku' => 'NIK-WRS',
                'tags' => ['nike', 'running', 'women', 'shoes'],
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
            ]

            // ── Home & Living ──
            [
                'name' => 'Robot Vacuum Cleaner',
                'slug' => 'robot-vacuum-cleaner',
                'price' => 29990,
                'compare_price' => 39990,
                'discount_percentage' => 25.01,
                'description' => 'Smart robot vacuum with LiDAR navigation, self-emptying base, and app control.',
                'short_description' => 'Smart robot vacuum with LiDAR',
                'category_slug' => 'home-living',
                'brand_slug' => null,
                'stock_quantity' => 25,
                'is_featured' => true,
                'average_rating' => 4.7,
                'reviews_count' => 145,
                'sales_count' => 560,
                'sku' => 'GEN-RVC',
                'tags' => ['vacuum', 'robot', 'smart-home', 'cleaning'],
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Memory Foam Pillow',
                'slug' => 'memory-foam-pillow',
                'price' => 2490,
                'compare_price' => 3490,
                'discount_percentage' => 28.65,
                'description' => 'Ergonomic memory foam pillow with cooling gel layer for better sleep.',
                'short_description' => 'Cooling gel memory foam pillow',
                'category_slug' => 'home-living',
                'brand_slug' => null,
                'stock_quantity' => 300,
                'is_best_seller' => true,
                'average_rating' => 4.6,
                'reviews_count' => 567,
                'sales_count' => 4500,
                'sku' => 'GEN-MFP',
                'tags' => ['pillow', 'memory-foam', 'sleep', 'ergonomic'],
                'image' => 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Smart Air Purifier',
                'slug' => 'smart-air-purifier',
                'price' => 18990,
                'compare_price' => 22990,
                'discount_percentage' => 17.4,
                'description' => 'HEPA H13 air purifier with real-time AQI display and Wi-Fi app control.',
                'short_description' => 'HEPA air purifier with Wi-Fi',
                'category_slug' => 'home-living',
                'brand_slug' => 'philips',
                'stock_quantity' => 35,
                'is_new_arrival' => true,
                'average_rating' => 4.5,
                'reviews_count' => 78,
                'sales_count' => 340,
                'sku' => 'PHI-SAP',
                'tags' => ['air-purifier', 'hepa', 'smart', 'philips'],
                'image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop',
            ]

            // ── Beauty & Health ──
            [
                'name' => 'Hair Dryer Professional',
                'slug' => 'hair-dryer-professional',
                'price' => 4990,
                'compare_price' => 6990,
                'discount_percentage' => 28.61,
                'description' => 'Ionic hair dryer with 3 heat settings and diffuser attachment.',
                'short_description' => 'Ionic hair dryer with diffuser',
                'category_slug' => 'beauty-health',
                'brand_slug' => 'philips',
                'stock_quantity' => 80,
                'is_flash_sale' => true,
                'average_rating' => 4.4,
                'reviews_count' => 234,
                'sales_count' => 1800,
                'sku' => 'PHI-HDP',
                'tags' => ['hair-dryer', 'ionic', 'beauty', 'philips'],
                'image' => 'https://images.unsplash.com/photo-1522338242992-e1a54571a7d8?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Protein Powder 2kg',
                'slug' => 'protein-powder-2kg',
                'price' => 3990,
                'compare_price' => 4990,
                'discount_percentage' => 20.04,
                'description' => 'Whey protein isolate 2kg tub with 25g protein per serving. Chocolate flavor.',
                'short_description' => 'Whey protein isolate 2kg',
                'category_slug' => 'beauty-health',
                'brand_slug' => null,
                'stock_quantity' => 120,
                'is_best_seller' => true,
                'average_rating' => 4.7,
                'reviews_count' => 456,
                'sales_count' => 3800,
                'sku' => 'GEN-PP2K',
                'tags' => ['protein', 'whey', 'fitness', 'supplement'],
                'image' => 'https://images.unsplash.com/photo-1593095948071-474c5cc2c129?w=600&h=600&fit=crop',
            ]

            // ── Sports & Outdoors ──
            [
                'name' => 'Cricket Bat English Willow',
                'slug' => 'cricket-bat-english-willow',
                'price' => 8990,
                'compare_price' => 10990,
                'discount_percentage' => 18.2,
                'description' => 'Professional grade English willow cricket bat with short handle.',
                'short_description' => 'Pro English willow cricket bat',
                'category_slug' => 'sports-outdoors',
                'brand_slug' => null,
                'stock_quantity' => 40,
                'is_featured' => true,
                'average_rating' => 4.8,
                'reviews_count' => 89,
                'sales_count' => 560,
                'sku' => 'GEN-CB',
                'tags' => ['cricket', 'bat', 'willow', 'sports'],
                'image' => 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Dumbbell Set 20kg',
                'slug' => 'dumbbell-set-20kg',
                'price' => 5990,
                'description' => 'Adjustable dumbbell set with 20kg total weight and carry case.',
                'short_description' => 'Adjustable 20kg dumbbell set',
                'category_slug' => 'sports-outdoors',
                'brand_slug' => null,
                'stock_quantity' => 60,
                'is_flash_sale' => true,
                'average_rating' => 4.5,
                'reviews_count' => 234,
                'sales_count' => 1900,
                'sku' => 'GEN-DB20',
                'tags' => ['dumbbell', 'gym', 'fitness', 'weights'],
                'image' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop',
            ]

            // ── Books ──
            [
                'name' => 'Atomic Habits by James Clear',
                'slug' => 'atomic-habits-james-clear',
                'price' => 590,
                'description' => 'The life-changing bestseller about building good habits and breaking bad ones.',
                'short_description' => 'Bestselling self-help book',
                'category_slug' => 'books-stationery',
                'brand_slug' => null,
                'stock_quantity' => 500,
                'is_best_seller' => true,
                'average_rating' => 4.9,
                'reviews_count' => 1234,
                'sales_count' => 8900,
                'sku' => 'BKS-AH',
                'tags' => ['book', 'self-help', 'habits', 'bestseller'],
                'image' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=600&fit=crop',
            ]
            [
                'name' => 'Notebook Set (3 Pack)',
                'slug' => 'notebook-set-3-pack',
                'price' => 450,
                'compare_price' => 600,
                'discount_percentage' => 25.0,
                'description' => 'Premium A5 ruled notebooks with hardcover. 200 pages each.',
                'short_description' => 'Premium A5 ruled notebooks',
                'category_slug' => 'books-stationery',
                'brand_slug' => null,
                'stock_quantity' => 800,
                'is_flash_sale' => true,
                'average_rating' => 4.3,
                'reviews_count' => 345,
                'sales_count' => 6700,
                'sku' => 'GEN-NB3P',
                'tags' => ['notebook', 'stationery', 'a5', 'ruled'],
                'image' => 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&h=600&fit=crop',
            ],
        ];

        $categories = Category::pluck('id', 'slug');
        $brands = Brand::pluck('id', 'slug');

        foreach ($products as $data) {
            $categoryId = $categories[$data['category_slug']] ?? null;
            $brandId = $data['brand_slug'] ? ($brands[$data['brand_slug']] ?? null) : null;

            if (!$categoryId) {
                $this->command?->warn("Category '{$data['category_slug']}' not found, skipping: {$data['name']}");
                continue;
            }

            $product = Product::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'name' => $data['name'],
                    'description' => $data['description'],
                    'short_description' => $data['short_description'] ?? '',
                    'price' => $data['price'],
                    'compare_price' => $data['compare_price'] ?? null,
                    'cost_price' => $data['price'] * 0.6,
                    'discount_percentage' => $data['discount_percentage'] ?? null,
                    'sku' => $data['sku'],
                    'stock_quantity' => $data['stock_quantity'],
                    'category_id' => $categoryId,
                    'brand_id' => $brandId,
                    'is_active' => true,
                    'is_featured' => $data['is_featured'] ?? false,
                    'is_flash_sale' => $data['is_flash_sale'] ?? false,
                    'is_best_seller' => $data['is_best_seller'] ?? false,
                    'is_new_arrival' => $data['is_new_arrival'] ?? false,
                    'average_rating' => $data['average_rating'] ?? 0,
                    'reviews_count' => $data['reviews_count'] ?? 0,
                    'sales_count' => $data['sales_count'] ?? 0,
                    'tags' => $data['tags'] ?? [],
                ]
            );

            ProductImage::updateOrCreate(
                ['product_id' => $product->id, 'sort_order' => 0],
                [
                    'image' => $data['image'] ?? 'products/placeholder.jpg',
                    'alt_text' => $product->name,
                    'is_primary' => true,
                ]
            );
        }

        $total = Product::count();
        $this->command?->info("Total products in database: {$total}");
    }
}
